name               = "aibarf"
main               = "src/index.js"
compatibility_date = "2025-06-13"
account_id         = "e311884653d907a208aec107614e8f02"
workers_dev        = false
route = "aibarf.com/*"

[[d1_databases]]
binding       = "DB"
database_name = "aibarf-core-v1"
database_id   = "d4aad340-2cb5-4dd5-a998-4d80f7adc8d8"

[[r2_buckets]]
binding     = "USER_IMAGES"
bucket_name = "user-images-v1"

[assets]
binding = "ASSETS"
directory = "./public"